permissions:
  contents: read

jobs:
  changes:
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    outputs:
      charts: ${{ steps.filter.outputs.charts }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - id: filter
        uses: dorny/paths-filter@v2.11.1
        with:
          filters: |
            charts:
              - 'charts/**/Chart.yaml'
              - 'charts/**/*'
          token: ${{ secrets.GITHUB_TOKEN }}
  helm-lint-test:
    if: ${{ needs.changes.outputs.charts == 'true' }}
    name: Helm chart
    needs:
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.pull_request.base.ref }}
      # Only build a kind cluster if there are chart changes to test.
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.pull_request.base.ref }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - if: steps.list-changed.outputs.changed == 'true'
        name: Create kind cluster
        uses: helm/kind-action@v1.12.0
      - if: steps.list-changed.outputs.changed == 'true'
        name: Run chart-testing (install)
        run: ct install --target-branch ${{ github.event.pull_request.base.ref }}
  helm-docs-validate:
    if: ${{ needs.changes.outputs.charts == 'true' }}
    name: Helm Docs
    needs:
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Run helm-docs
        uses: docker://jnorwood/helm-docs:v1.14.2
      - name: Check for changes
        run: |
          if ! git diff --exit-code charts/*/README.md; then
            echo "ERROR: Helm chart README.md files are out of date"
            echo "Run from charts/: docker run --rm --volume \"\$(pwd):/helm-docs\" -u \$(id -u) jnorwood/helm-docs:v1.14.2"
            exit 1
          fi

name: Lint and Test Charts
on: pull_request
